import test from "node:test";
import assert from "node:assert/strict";
import {KnowledgeIngestionPipeline,KnowledgeIndex,EvidenceAwareRetriever,ProvenanceManager,KnowledgeConflictResolver,MemoryConsolidationEngine,FailurePatternLibrary,StrategyEffectivenessModel,ExperienceGuidedPlanner,ContinuousLearningLoop} from "../src/core/autonomous-knowledge.js";
import {KnowledgeStore} from "../src/core/knowledge-store.js";
import {LearningMemory} from "../src/core/learning-memory.js";

test("ingestion stores provenance and retrieval ranks evidence",async()=>{const k=new KnowledgeStore();const p=new KnowledgeIngestionPipeline({knowledgeStore:k});await p.ingest({items:[{id:"a",title:"A",content:"secure deployment"}],source:"docs",sourceVersion:"1"});const r=await new EvidenceAwareRetriever({knowledgeStore:k}).retrieve({query:"secure deployment"});assert.equal(r.length,1);assert.ok(r[0].retrievalScore>0);});
test("provenance validation and conflict resolution work",async()=>{const k=new KnowledgeStore();await k.upsert({id:"a",title:"same",content:"x",metadata:{provenance:{source:"a",authority:.2}}});await k.upsert({id:"b",title:"same",content:"y",metadata:{provenance:{source:"b",authority:.9}}});const c=new KnowledgeConflictResolver().resolve(await k.list());assert.equal(c.resolved[0].id,"b");assert.equal(c.conflicts.length,1);assert.equal(new ProvenanceManager().validate({metadata:{provenance:{source:"x",updatedAt:"now"}}}).passed,true);});
test("memory consolidation creates durable lessons",async()=>{const l=new LearningMemory();await l.record({candidate:{id:"1"},outcome:"SUCCESS",strategy:"test",lessons:["use tests"]});await l.record({candidate:{id:"2"},outcome:"SUCCESS",strategy:"test",lessons:["use tests"]});const k=new KnowledgeStore();const out=await new MemoryConsolidationEngine({learningMemory:l,knowledgeStore:k}).consolidate();assert.equal(out.length,1);});
test("failure patterns and strategy model learn from outcomes",async()=>{const k=new KnowledgeStore();const f=new FailurePatternLibrary({knowledgeStore:k});await f.record({failureType:"CI",message:"failed",strategy:"repair",success:true});assert.equal((await f.strategies("CI"))[0].strategy,"repair");const l=new LearningMemory();await l.record({candidate:{id:"1"},outcome:"SUCCESS",strategy:"repair"});const s=await new StrategyEffectivenessModel({learningMemory:l}).score("repair");assert.equal(s.successRate,1);});
test("experience guided planner and continuous loop feed learning",async()=>{const l=new LearningMemory();await l.record({candidate:{id:"1"},outcome:"SUCCESS",strategy:"repair",lessons:["repair first"]});const k=new KnowledgeStore();const loop=new ContinuousLearningLoop({learningMemory:l,knowledgeStore:k,consolidator:new MemoryConsolidationEngine({learningMemory:l,knowledgeStore:k})});await loop.learn({candidate:{id:"2"},outcome:"SUCCESS",strategy:"repair",lessons:["repair first"]});const p=new ExperienceGuidedPlanner({strategyModel:new StrategyEffectivenessModel({learningMemory:l}),learningMemory:l});const x=await p.plan({id:"task"});assert.equal(x.executionStrategy,"repair");});
