import test from "node:test";
import assert from "node:assert/strict";
import {ArchitectureRegressionIntelligence,SystemDependencyIntelligence,AutonomousSecurityArchitect,SLOAwareRecoveryController,AutonomousProgramDirector,AutonomousArchitectCore} from "../src/core/autonomous-architect-core.js";

test("architecture regression detects structural drift",async()=>{const r=new ArchitectureRegressionIntelligence({threshold:.2});const base={id:"a",components:[{id:"api",dependsOn:[]},{id:"db",dependsOn:[]} ]};const c={id:"b",components:[{id:"api",dependsOn:["db"]},{id:"worker",dependsOn:[]} ]};const out=await r.compare({candidate:c,baseline:base});assert.equal(out.passed,false);assert.ok(out.changes.added.includes("worker"));});
test("dependency intelligence models and propagates impact",()=>{const d=new SystemDependencyIntelligence();const graph=d.model({architecture:{components:[{id:"api",dependsOn:["core"]},{id:"core",dependsOn:[]}]},services:[{id:"db"}]});assert.equal(graph.nodes.length,3);assert.deepEqual(d.impact(["component:core"]),["component:core","component:api"]);});
test("security architecture requires isolation and least privilege",()=>{const s=new AutonomousSecurityArchitect();const design=s.design({contract:{id:"a"}});assert.equal(s.validate(design).passed,true);assert.equal(s.validate({...design,networkPolicy:"allow-all"}).passed,false);});
test("SLO controller triggers bounded recovery",async()=>{let called=null;const s=new SLOAwareRecoveryController({recovery:{handle:async a=>{called=a;return {status:"RECOVERED"};}},slos:{maxFailureRate:.05}});const out=await s.recover({failureRate:.2});assert.equal(out.status,"RECOVERY_REQUESTED");assert.equal(called.alertType,"HIGH_FAILURE_RATE");});
test("architect core integrates plan, security and dependencies",async()=>{const architect={plan:async()=>({contract:{id:"a",components:[{id:"api",dependsOn:[]}]},agentTeam:[]})};const core=new AutonomousArchitectCore({architect,securityArchitect:new AutonomousSecurityArchitect(),dependencyIntelligence:new SystemDependencyIntelligence()});const plan=await core.plan({objective:"x",context:{}});assert.equal(plan.securityValidation.passed,true);assert.equal(plan.dependencies.nodes.length,1);});
test("program director governs and executes one objective",async()=>{let stages=[];const director=new AutonomousProgramDirector({architect:{plan:async()=>({contract:{id:"a"}})},missionRunner:{run:async()=>({status:"COMPLETED"})},policy:{authorize:async({stage})=>{stages.push(stage);}}});const out=await director.run({objective:"ship"});assert.equal(out.status,"COMPLETED");assert.deepEqual(stages,["PLAN","EXECUTE"]);});
