export function runtimeConfig(env=process.env){
  return {
    model:{apiKey:env.OPENAI_API_KEY,baseUrl:env.JORA_MODEL_BASE_URL,model:env.JORA_MODEL},
    github:{token:env.GITHUB_TOKEN,owner:env.JORA_GITHUB_OWNER,repo:env.JORA_GITHUB_REPO,branch:env.JORA_GITHUB_BRANCH||"main"},
    workspace:env.JORA_WORKSPACE||"./.jora/workspace",
    docker:{image:env.JORA_DOCKER_IMAGE||"node:20-bookworm-slim",network:env.JORA_DOCKER_NETWORK||"none"},
    persistence:env.JORA_STATE_FILE||"./.jora/executions.json",
    championStateFile:env.JORA_CHAMPION_STATE_FILE||"./.jora/champion.json",
    observabilityStateFile:env.JORA_OBSERVABILITY_STATE_FILE||"./.jora/observability.json",
    ci:{
      timeoutMs:Number(env.JORA_CI_TIMEOUT_MS||600000),
      pollMs:Number(env.JORA_CI_POLL_MS||5000)
    },
    autonomous:{
      maxCycles:Number(env.JORA_AUTONOMOUS_MAX_CYCLES||4)
    },
    deployment:{
      enabled:env.JORA_DEPLOYMENT_ENABLED==="true",
      webhookUrl:env.JORA_DEPLOYMENT_WEBHOOK_URL,
      healthUrl:env.JORA_HEALTHCHECK_URL,
      healthAttempts:Number(env.JORA_HEALTHCHECK_ATTEMPTS||3),
      healthIntervalMs:Number(env.JORA_HEALTHCHECK_INTERVAL_MS||2000),
      timeoutMs:Number(env.JORA_DEPLOYMENT_TIMEOUT_MS||60000),
      staging:{
        enabled:env.JORA_STAGING_DEPLOYMENT_ENABLED==="true" || Boolean(env.JORA_STAGING_DEPLOYMENT_WEBHOOK_URL),
        webhookUrl:env.JORA_STAGING_DEPLOYMENT_WEBHOOK_URL,
        healthUrl:env.JORA_STAGING_HEALTHCHECK_URL,
        healthAttempts:Number(env.JORA_STAGING_HEALTHCHECK_ATTEMPTS||3),
        healthIntervalMs:Number(env.JORA_STAGING_HEALTHCHECK_INTERVAL_MS||2000)
      },
      production:{
        webhookUrl:env.JORA_PRODUCTION_DEPLOYMENT_WEBHOOK_URL||env.JORA_DEPLOYMENT_WEBHOOK_URL,
        healthUrl:env.JORA_PRODUCTION_HEALTHCHECK_URL||env.JORA_HEALTHCHECK_URL,
        healthAttempts:Number(env.JORA_PRODUCTION_HEALTHCHECK_ATTEMPTS||env.JORA_HEALTHCHECK_ATTEMPTS||3),
        healthIntervalMs:Number(env.JORA_PRODUCTION_HEALTHCHECK_INTERVAL_MS||env.JORA_HEALTHCHECK_INTERVAL_MS||2000)
      }
    },
    api:{\n      enabled:env.JORA_API_ENABLED==="true",\n      host:env.JORA_API_HOST||"127.0.0.1",\n      port:Number(env.JORA_API_PORT||8787),\n      authToken:env.JORA_API_AUTH_TOKEN,\n      maxBodyBytes:Number(env.JORA_API_MAX_BODY_BYTES||1000000)\n    },\n    distributed:{
      enabled:env.JORA_DISTRIBUTED_ENABLED==="true",
      databaseUrl:env.JORA_DATABASE_URL||env.DATABASE_URL,
      leaseNamespace:env.JORA_LEASE_NAMESPACE||"jora-worker",
      leaseTtlMs:Number(env.JORA_LEASE_TTL_MS||120000),
      maxConnections:Number(env.JORA_DATABASE_MAX_CONNECTIONS||5),
      owner:env.JORA_WORKER_ID||"jora-worker"
    },
    worker:{
      intervalMs:Number(env.JORA_WORK_INTERVAL_MS||60000),
      maxCycles:env.JORA_MAX_CYCLES?Number(env.JORA_MAX_CYCLES):Infinity,
      stateFile:env.JORA_WORKER_STATE_FILE||"./.jora/worker.json",
      heartbeatMs:Number(env.JORA_WORKER_HEARTBEAT_MS||10000),
      staleAfterMs:Number(env.JORA_WORKER_STALE_AFTER_MS||120000)
    }
  };
}
